server {
    listen 80;
    server_name _; # Catches all requests not matched by other server_names on port 80

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html; # Essential for Angular routing
    }
}