/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardReportsIndexRouteImport } from './routes/dashboard.reports.index'
import { Route as DashboardReportsAddRouteImport } from './routes/dashboard.reports.add'
import { Route as DashboardTabsIndexRouteImport } from './routes/dashboard.tabs.index'
import { Route as DashboardTabsAddRouteImport } from './routes/dashboard.tabs.add'
import { Route as DashboardReportsReportIdIndexRouteImport } from './routes/dashboard.reports.$reportId.index'
import { Route as DashboardReportsReportIdEditRouteImport } from './routes/dashboard.reports.$reportId.edit'
import { Route as DashboardTabsTabIdIndexRouteImport } from './routes/dashboard.tabs.$tabId.index'
import { Route as DashboardTabsTabIdEditRouteImport } from './routes/dashboard.tabs.$tabId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsIndexRoute = DashboardReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsAddRoute = DashboardReportsAddRouteImport.update({
  id: '/reports/add',
  path: '/reports/add',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTabsIndexRoute = DashboardTabsIndexRouteImport.update({
  id: '/tabs/',
  path: '/tabs/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTabsAddRoute = DashboardTabsAddRouteImport.update({
  id: '/tabs/add',
  path: '/tabs/add',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsReportIdIndexRoute =
  DashboardReportsReportIdIndexRouteImport.update({
    id: '/reports/$reportId/',
    path: '/reports/$reportId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardReportsReportIdEditRoute =
  DashboardReportsReportIdEditRouteImport.update({
    id: '/reports/$reportId/edit',
    path: '/reports/$reportId/edit',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTabsTabIdIndexRoute = DashboardTabsTabIdIndexRouteImport.update({
  id: '/tabs/$tabId/',
  path: '/tabs/$tabId/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTabsTabIdEditRoute = DashboardTabsTabIdEditRouteImport.update({
  id: '/tabs/$tabId/edit',
  path: '/tabs/$tabId/edit',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/reports/add': typeof DashboardReportsAddRoute
  '/dashboard/tabs/add': typeof DashboardTabsAddRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/dashboard/tabs/': typeof DashboardTabsIndexRoute
  '/dashboard/reports/$reportId/edit': typeof DashboardReportsReportIdEditRoute
  '/dashboard/tabs/$tabId/edit': typeof DashboardTabsTabIdEditRoute
  '/dashboard/reports/$reportId/': typeof DashboardReportsReportIdIndexRoute
  '/dashboard/tabs/$tabId/': typeof DashboardTabsTabIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/reports/add': typeof DashboardReportsAddRoute
  '/dashboard/tabs/add': typeof DashboardTabsAddRoute
  '/dashboard/reports': typeof DashboardReportsIndexRoute
  '/dashboard/tabs': typeof DashboardTabsIndexRoute
  '/dashboard/reports/$reportId/edit': typeof DashboardReportsReportIdEditRoute
  '/dashboard/tabs/$tabId/edit': typeof DashboardTabsTabIdEditRoute
  '/dashboard/reports/$reportId': typeof DashboardReportsReportIdIndexRoute
  '/dashboard/tabs/$tabId': typeof DashboardTabsTabIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/reports/add': typeof DashboardReportsAddRoute
  '/dashboard/tabs/add': typeof DashboardTabsAddRoute
  '/dashboard/reports/': typeof DashboardReportsIndexRoute
  '/dashboard/tabs/': typeof DashboardTabsIndexRoute
  '/dashboard/reports/$reportId/edit': typeof DashboardReportsReportIdEditRoute
  '/dashboard/tabs/$tabId/edit': typeof DashboardTabsTabIdEditRoute
  '/dashboard/reports/$reportId/': typeof DashboardReportsReportIdIndexRoute
  '/dashboard/tabs/$tabId/': typeof DashboardTabsTabIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/reports/add'
    | '/dashboard/tabs/add'
    | '/dashboard/reports/'
    | '/dashboard/tabs/'
    | '/dashboard/reports/$reportId/edit'
    | '/dashboard/tabs/$tabId/edit'
    | '/dashboard/reports/$reportId/'
    | '/dashboard/tabs/$tabId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dashboard/reports/add'
    | '/dashboard/tabs/add'
    | '/dashboard/reports'
    | '/dashboard/tabs'
    | '/dashboard/reports/$reportId/edit'
    | '/dashboard/tabs/$tabId/edit'
    | '/dashboard/reports/$reportId'
    | '/dashboard/tabs/$tabId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/'
    | '/dashboard/reports/add'
    | '/dashboard/tabs/add'
    | '/dashboard/reports/'
    | '/dashboard/tabs/'
    | '/dashboard/reports/$reportId/edit'
    | '/dashboard/tabs/$tabId/edit'
    | '/dashboard/reports/$reportId/'
    | '/dashboard/tabs/$tabId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/': {
      id: '/dashboard/reports/'
      path: '/reports'
      fullPath: '/dashboard/reports/'
      preLoaderRoute: typeof DashboardReportsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/add': {
      id: '/dashboard/reports/add'
      path: '/reports/add'
      fullPath: '/dashboard/reports/add'
      preLoaderRoute: typeof DashboardReportsAddRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tabs/': {
      id: '/dashboard/tabs/'
      path: '/tabs'
      fullPath: '/dashboard/tabs/'
      preLoaderRoute: typeof DashboardTabsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tabs/add': {
      id: '/dashboard/tabs/add'
      path: '/tabs/add'
      fullPath: '/dashboard/tabs/add'
      preLoaderRoute: typeof DashboardTabsAddRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/$reportId/': {
      id: '/dashboard/reports/$reportId/'
      path: '/reports/$reportId'
      fullPath: '/dashboard/reports/$reportId/'
      preLoaderRoute: typeof DashboardReportsReportIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports/$reportId/edit': {
      id: '/dashboard/reports/$reportId/edit'
      path: '/reports/$reportId/edit'
      fullPath: '/dashboard/reports/$reportId/edit'
      preLoaderRoute: typeof DashboardReportsReportIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tabs/$tabId/': {
      id: '/dashboard/tabs/$tabId/'
      path: '/tabs/$tabId'
      fullPath: '/dashboard/tabs/$tabId/'
      preLoaderRoute: typeof DashboardTabsTabIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tabs/$tabId/edit': {
      id: '/dashboard/tabs/$tabId/edit'
      path: '/tabs/$tabId/edit'
      fullPath: '/dashboard/tabs/$tabId/edit'
      preLoaderRoute: typeof DashboardTabsTabIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardReportsAddRoute: typeof DashboardReportsAddRoute
  DashboardTabsAddRoute: typeof DashboardTabsAddRoute
  DashboardReportsIndexRoute: typeof DashboardReportsIndexRoute
  DashboardTabsIndexRoute: typeof DashboardTabsIndexRoute
  DashboardReportsReportIdEditRoute: typeof DashboardReportsReportIdEditRoute
  DashboardTabsTabIdEditRoute: typeof DashboardTabsTabIdEditRoute
  DashboardReportsReportIdIndexRoute: typeof DashboardReportsReportIdIndexRoute
  DashboardTabsTabIdIndexRoute: typeof DashboardTabsTabIdIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardReportsAddRoute: DashboardReportsAddRoute,
  DashboardTabsAddRoute: DashboardTabsAddRoute,
  DashboardReportsIndexRoute: DashboardReportsIndexRoute,
  DashboardTabsIndexRoute: DashboardTabsIndexRoute,
  DashboardReportsReportIdEditRoute: DashboardReportsReportIdEditRoute,
  DashboardTabsTabIdEditRoute: DashboardTabsTabIdEditRoute,
  DashboardReportsReportIdIndexRoute: DashboardReportsReportIdIndexRoute,
  DashboardTabsTabIdIndexRoute: DashboardTabsTabIdIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
